#------------------------------------------------------------------------------#
# INSTALL DEPENDENCIES FOR RUNNING DES OF
# SICK SICKER MODEL WITH RECURRENCE

#* Authors: 
#* - XXXXX
#* - XXXXX
#* - XXXXX
#------------------------------------------------------------------------------#
#* Please cite the article(s) when using this code
#* XXXXX open article
#* doi: XXXXX
#* bibtex: XXXXX
#------------------------------------------------------------------------------#
#------------------------------------------------------------------------------#
# Description ----
#* For contributors of the repository, we encourage using the same environment as the developer of the code. 
#* For this we suggest using the package 'renv'. 

#* 1. Ensure package renv is installed, and restores project library version from
#* renv.lock.
#* 2. Check for currently installed dependencies and installs any require dependency 
#* that may be missing.
#* 3. Restore project library (developer's version)
#------------------------------------------------------------------------------#


# 0. Check R version 3.5 or newer 
if (getRversion() >= "3.5.0") {
  message("R version is 3.5.0 or newer.")
} else {
  stop("R version is older than 3.5.0.")
}

# 1. Ensure renv is available
if (!requireNamespace("renv", quietly = FALSE)) {
  message("Installing package 'renv' ")
  install.packages("renv")
}

# 2.  Required packages
required_pkgs <- c(
  "data.table"  ,   # to manipulate data
  "dplyr"       ,   # to manipulate data

  "ggplot2"     ,   # to visualize data
  "ggrepel"     ,   # to visualize data
  "ellipse"     ,   # to visualize data

  "patchwork"   ,   # for combining ggplot2 figures

  "doParallel"  ,   # parallel processing
  "parallel"    ,   # parallel processing
  "foreach"     ,   # parallel processing
  "abind"       ,   # manipulate multidimensional arrays
  
  "MethylCapSig",   # has nice multivariate lognormal random variable generator
  
  "matrixStats"   # functions operating on rows and columns of matrices (optional)
  
)

installed_pkgs   <- rownames(installed.packages())          
to_install_pkgs  <- setdiff(required_pkgs, installed_pkgs)

# Install missing packages
if (length(to_install_pkgs)) {
  
  message("Installing missing required packages: ", paste(to_install_pkgs, collapse = ", "))
  failed_pkgs <- character()
  
  for (pkg in to_install_pkgs) {
    message("→ Installing ", pkg, " …")
    tryCatch(
      install.packages(pkg, dependencies = TRUE),
      error = function(e) {
        warning(sprintf("  ✗ Failed to install '%s': %s", pkg, e$message))
        failed_pkgs <<- c(failed_pkgs, pkg)
      }
    )
  }
  
  if (length(failed_pkgs)) {
    warning(
      "The following packages could not be installed:\n",
      paste0(" - ", failed_pkgs, collapse = "\n")
    )
  }
}


# 3. Restore the project library from renv.lock
message("Restoring project's dependencies from the lockfile, as previously generated by the developer")
renv::restore(prompt = T)


message("Setup complete!")

